### ISSUE TITLE
Initializing dependant parameters in the config

### ISSUE THREAD

**Issue by nkhedekar** [MIT-SPARK/config_utilities#14]
The previous version of config_utilities had the provision for having dependant that can be initialized with a special function. Ref: https://github.com/ethz-asl/config_utilities?tab=readme-ov-file#virtual-member-functions . What is the recommended/correct way to do this in this version?

**Comment by Schmluk** [comment]
Hi @nkhedekar,

We found that this feature is not very frequently used and have not implemented an exact replication (although such a feature could be added). In particular, for this version we intended the design to be more open to handle any config structs in a more typical C++ fashion. The desired behavior could be implemented by either directly modifying the struct:
```c++
auto config = fromYaml<Config>(data);
config.y = config.x * 2;
```

The other option is to put it into the config declaration:
```c++
void declare_config(Config& config) {
  field(config.x, "x");
  config.y = config.y * 2;  
}
```
Note that this will overwrite y also when getting or checking the config.

As a third alternative, we found that making all config params explicit and having the user set them results in a clearer and more interpretable config/code flow:
```c++
void declare_config(Config& config) {
  field(config.x, "x");
  field(config.y, "y");
  checkCondition(config.y == config.x * 2, "x must be 2* y");
}
```
A similar option would be to make the default value invalid, so the user has to set the param.

Hope this helps!

**Comment by nkhedekar** [comment]
Yep, it does! Thank you for the detailed response and the multiple suggestions :slightly_smiling_face:

**Comment by nkhedekar** [comment]
For future reference, there seem to be some vectors that are empty in one of the subsequent passes made when `checkValid()` is used and dependant variables are initialized in `declare_config()`. Particularly one of my dependant parameters is initialized based on the size of an `std::vector` like `dep = 1/vec.size()`. In the subsequent passes over `declare_config()` when I use `checkValid()` it seems that the `vec` is not populated leading to a divide by zero error. Without investigating further, a quick fix I'm using is having a `static bool flag` inside `declare_config()` to ensure that dependant parameters only get set in the first pass.

**Comment by Schmluk** [comment]
That could definitively be a solution. Alternatively, the proper way to handle this specific case would probably be to have these fields be const members of the config-using class, that are initialized after the config is given and checked. That would also clearer make it for the user that e.g. 1/vec.size is not configurable, but a cached value given the config.
